### ISSUE TITLE
Why is this a standalone module?

### ISSUE THREAD

**Issue by JonRoma** [techservicesillinois/terraform-aws-ecs-shibd-data-sealer-role#3]
@ddriddle, do you recall why we created this code in a standalone module? At first glance, this seems suitable to have been a submodule within `as-aws-module` (which today has been partially supplanted by `terraform-aws-iam`? I don't remember the history of this.

**Comment by ddriddle** [comment]
@JonRoma The reason it did not go into the `as-aws-module` repo is because this code was intended for use by the public. The other roles that went into `as-aws-module` were generally tied to a specific service. I believe this code is used with `shib-in-a-box` which was presented at an IT Pro Forum.

**Comment by JonRoma** [comment]
Thanks, @ddriddle. Perhaps this code can be retired when we retire Shib-In-a-Box, which Andy has proposed take place at the end of the calendar year. Gratias responsum.

**Comment by ddriddle** [comment]
@JonRoma I think you are right that you can retire it when Shib-in-a-box is retired, but do double check that this is not also used by the IdP. You may also be able to retire this related repo: https://github.com/techservicesillinois/terraform-aws-shibd-data-sealer.
